---
title: "Hwk2: Question 5"
output: html_notebook
Student: Jonathan Herrera
---

```{r}
library(neuralnet)
train<-read.table("nine.instances.txt",sep=",",header=T)
train
```
```{r}
plot(train$X1,train$X2,col=c("black","red")[train$Label+1],xlim=c(-2,2),ylim=c(-2,2))
```

```{r}
net<-neuralnet(Label~X1+X2,train,hidden=3,rep=5)
net
```

```{r}
plot(net,rep="best")
```

```{r}
findinterceptslope<-function(w)
{
slope<-w[2]/w[3]*(-1)
intercept<-w[1]/w[3]*(-1)
rvector<-c(intercept,slope)
return(rvector)
}
w1<-c(5.52417,-6.29554,-2.52652)
line1<-findinterceptslope(w1)
line1
```
Decision surface of each hidden node 1
```{r}
w2<-c(-5.12896,-3.2551,1.80801)
line2<-findinterceptslope(w2)
line2
```
Decision surface of each hidden node 2
```{r}
w3<-c(3.55647,3.42392,9.00276)
line3<-findinterceptslope(w3)
line3
```
Decision surface of each hidden node 3
```{r}
plot(train$X1,train$X2,col=c("black","red")[train$Label+1],xlim=c(-2,2),ylim=c(-2,2), main="Decision surfaces of all hidden nodes")
abline(line1[1],line1[2],col="green",lty=2)
abline(line2[1],line2[2],col="blue",lty=2)
abline(line3[1],line3[2],col="cyan",lty=2)
```
End of answer 5